-- Generated by d-migrate 0.9.12
-- Source: neutral schema v1.0.0 "b-cad"
-- Target: sqlite

CREATE TABLE "projects" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "name" TEXT NOT NULL,
    "file_version" INTEGER DEFAULT 1,
    "unit" TEXT DEFAULT 'mm',
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL
);

-- [W200] Decimal(12,3) mapped to REAL in SQLite. Precision may be lost.
-- Hint: Store as TEXT if exact decimal precision is required.
-- [W200] Decimal(12,3) mapped to REAL in SQLite. Precision may be lost.
-- Hint: Store as TEXT if exact decimal precision is required.
CREATE TABLE "storeys" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "project_id" INTEGER NOT NULL REFERENCES "projects"("id") ON DELETE CASCADE,
    "name" TEXT NOT NULL,
    "level_index" INTEGER NOT NULL,
    "elevation_mm" REAL NOT NULL,
    "height_mm" REAL NOT NULL,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    CONSTRAINT "uq_storeys_project_level" UNIQUE ("project_id", "level_index")
);

-- [W200] Decimal(10,3) mapped to REAL in SQLite. Precision may be lost.
-- Hint: Store as TEXT if exact decimal precision is required.
-- [W200] Decimal(6,3) mapped to REAL in SQLite. Precision may be lost.
-- Hint: Store as TEXT if exact decimal precision is required.
-- [W200] Decimal(12,2) mapped to REAL in SQLite. Precision may be lost.
-- Hint: Store as TEXT if exact decimal precision is required.
-- [W200] Decimal(12,2) mapped to REAL in SQLite. Precision may be lost.
-- Hint: Store as TEXT if exact decimal precision is required.
CREATE TABLE "materials" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "project_id" INTEGER NOT NULL REFERENCES "projects"("id") ON DELETE CASCADE,
    "name" TEXT NOT NULL,
    "category" TEXT NOT NULL,
    "color_hex" TEXT,
    "texture_path" TEXT,
    "density" REAL,
    "u_value" REAL,
    "cost_per_m2" REAL,
    "cost_per_m3" REAL
);

CREATE TABLE "layers" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "project_id" INTEGER NOT NULL REFERENCES "projects"("id") ON DELETE CASCADE,
    "name" TEXT NOT NULL,
    "visible" INTEGER DEFAULT 1,
    "locked" INTEGER DEFAULT 0,
    "color_hex" TEXT,
    CONSTRAINT "uq_layers_project_name" UNIQUE ("project_id", "name")
);

CREATE TABLE "documents" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "project_id" INTEGER NOT NULL REFERENCES "projects"("id") ON DELETE CASCADE,
    "document_type" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "scale" TEXT,
    "settings_json" TEXT
);

CREATE TABLE "undo_commands" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "project_id" INTEGER NOT NULL REFERENCES "projects"("id") ON DELETE CASCADE,
    "command_index" INTEGER NOT NULL,
    "command_type" TEXT NOT NULL,
    "payload_json" TEXT NOT NULL,
    "created_at" TEXT NOT NULL,
    CONSTRAINT "uq_undo_project_index" UNIQUE ("project_id", "command_index")
);

-- [W200] Decimal(14,4) mapped to REAL in SQLite. Precision may be lost.
-- Hint: Store as TEXT if exact decimal precision is required.
-- [W200] Decimal(12,3) mapped to REAL in SQLite. Precision may be lost.
-- Hint: Store as TEXT if exact decimal precision is required.
-- [W200] Decimal(14,4) mapped to REAL in SQLite. Precision may be lost.
-- Hint: Store as TEXT if exact decimal precision is required.
CREATE TABLE "rooms" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "project_id" INTEGER NOT NULL REFERENCES "projects"("id") ON DELETE CASCADE,
    "storey_id" INTEGER NOT NULL REFERENCES "storeys"("id") ON DELETE CASCADE,
    "name" TEXT NOT NULL,
    "room_type" TEXT NOT NULL,
    "area_m2" REAL,
    "perimeter_mm" REAL,
    "volume_m3" REAL,
    "polygon_json" TEXT NOT NULL,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL
);

-- [W200] Decimal(12,3) mapped to REAL in SQLite. Precision may be lost.
-- Hint: Store as TEXT if exact decimal precision is required.
-- [W200] Decimal(12,3) mapped to REAL in SQLite. Precision may be lost.
-- Hint: Store as TEXT if exact decimal precision is required.
-- [W200] Decimal(12,3) mapped to REAL in SQLite. Precision may be lost.
-- Hint: Store as TEXT if exact decimal precision is required.
-- [W200] Decimal(12,3) mapped to REAL in SQLite. Precision may be lost.
-- Hint: Store as TEXT if exact decimal precision is required.
-- [W200] Decimal(12,3) mapped to REAL in SQLite. Precision may be lost.
-- Hint: Store as TEXT if exact decimal precision is required.
CREATE TABLE "stairs" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "project_id" INTEGER NOT NULL REFERENCES "projects"("id") ON DELETE CASCADE,
    "from_storey_id" INTEGER NOT NULL REFERENCES "storeys"("id") ON DELETE RESTRICT,
    "to_storey_id" INTEGER NOT NULL REFERENCES "storeys"("id") ON DELETE RESTRICT,
    "name" TEXT,
    "stair_type" TEXT NOT NULL,
    "start_x_mm" REAL NOT NULL,
    "start_y_mm" REAL NOT NULL,
    "width_mm" REAL NOT NULL,
    "step_count" INTEGER NOT NULL,
    "rise_mm" REAL NOT NULL,
    "tread_mm" REAL NOT NULL
);

-- [W200] Decimal(12,3) mapped to REAL in SQLite. Precision may be lost.
-- Hint: Store as TEXT if exact decimal precision is required.
-- [W200] Decimal(12,3) mapped to REAL in SQLite. Precision may be lost.
-- Hint: Store as TEXT if exact decimal precision is required.
-- [W200] Decimal(12,3) mapped to REAL in SQLite. Precision may be lost.
-- Hint: Store as TEXT if exact decimal precision is required.
-- [W200] Decimal(7,3) mapped to REAL in SQLite. Precision may be lost.
-- Hint: Store as TEXT if exact decimal precision is required.
-- [W200] Decimal(8,4) mapped to REAL in SQLite. Precision may be lost.
-- Hint: Store as TEXT if exact decimal precision is required.
-- [W200] Decimal(8,4) mapped to REAL in SQLite. Precision may be lost.
-- Hint: Store as TEXT if exact decimal precision is required.
-- [W200] Decimal(8,4) mapped to REAL in SQLite. Precision may be lost.
-- Hint: Store as TEXT if exact decimal precision is required.
CREATE TABLE "objects" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "project_id" INTEGER NOT NULL REFERENCES "projects"("id") ON DELETE CASCADE,
    "storey_id" INTEGER NOT NULL REFERENCES "storeys"("id") ON DELETE CASCADE,
    "object_type" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "x_mm" REAL NOT NULL,
    "y_mm" REAL NOT NULL,
    "z_mm" REAL DEFAULT 0,
    "rotation_deg" REAL DEFAULT 0,
    "scale_x" REAL DEFAULT 1,
    "scale_y" REAL DEFAULT 1,
    "scale_z" REAL DEFAULT 1,
    "params_json" TEXT
);

-- [W200] Decimal(12,3) mapped to REAL in SQLite. Precision may be lost.
-- Hint: Store as TEXT if exact decimal precision is required.
CREATE TABLE "wall_types" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "project_id" INTEGER NOT NULL REFERENCES "projects"("id") ON DELETE CASCADE,
    "name" TEXT NOT NULL,
    "default_thickness_mm" REAL NOT NULL,
    "is_load_bearing" INTEGER DEFAULT 0,
    "material_id" INTEGER REFERENCES "materials"("id") ON DELETE RESTRICT
);

-- [W200] Decimal(7,3) mapped to REAL in SQLite. Precision may be lost.
-- Hint: Store as TEXT if exact decimal precision is required.
-- [W200] Decimal(12,3) mapped to REAL in SQLite. Precision may be lost.
-- Hint: Store as TEXT if exact decimal precision is required.
-- [W200] Decimal(12,3) mapped to REAL in SQLite. Precision may be lost.
-- Hint: Store as TEXT if exact decimal precision is required.
-- [W200] Decimal(12,3) mapped to REAL in SQLite. Precision may be lost.
-- Hint: Store as TEXT if exact decimal precision is required.
CREATE TABLE "roofs" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "project_id" INTEGER NOT NULL REFERENCES "projects"("id") ON DELETE CASCADE,
    "storey_id" INTEGER NOT NULL REFERENCES "storeys"("id") ON DELETE CASCADE,
    "roof_type" TEXT NOT NULL CHECK ("roof_type" IN ('sattel', 'walm', 'pult')),
    "pitch_deg" REAL DEFAULT 30,
    "overhang_mm" REAL DEFAULT 500,
    "height_mm" REAL,
    "thickness_mm" REAL DEFAULT 200,
    "footprint_json" TEXT NOT NULL,
    "material_id" INTEGER REFERENCES "materials"("id") ON DELETE RESTRICT
);

-- [W200] Decimal(12,3) mapped to REAL in SQLite. Precision may be lost.
-- Hint: Store as TEXT if exact decimal precision is required.
CREATE TABLE "slabs" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "project_id" INTEGER NOT NULL REFERENCES "projects"("id") ON DELETE CASCADE,
    "storey_id" INTEGER NOT NULL REFERENCES "storeys"("id") ON DELETE CASCADE,
    "slab_type" TEXT NOT NULL,
    "thickness_mm" REAL NOT NULL,
    "polygon_json" TEXT NOT NULL,
    "material_id" INTEGER REFERENCES "materials"("id") ON DELETE RESTRICT
);

CREATE TABLE "entity_layers" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "project_id" INTEGER NOT NULL REFERENCES "projects"("id") ON DELETE CASCADE,
    "entity_type" TEXT NOT NULL,
    "entity_id" INTEGER NOT NULL,
    "layer_id" INTEGER NOT NULL REFERENCES "layers"("id") ON DELETE CASCADE
);

-- [W200] Decimal(12,3) mapped to REAL in SQLite. Precision may be lost.
-- Hint: Store as TEXT if exact decimal precision is required.
-- [W200] Decimal(12,3) mapped to REAL in SQLite. Precision may be lost.
-- Hint: Store as TEXT if exact decimal precision is required.
-- [W200] Decimal(12,3) mapped to REAL in SQLite. Precision may be lost.
-- Hint: Store as TEXT if exact decimal precision is required.
-- [W200] Decimal(12,3) mapped to REAL in SQLite. Precision may be lost.
-- Hint: Store as TEXT if exact decimal precision is required.
-- [W200] Decimal(12,3) mapped to REAL in SQLite. Precision may be lost.
-- Hint: Store as TEXT if exact decimal precision is required.
-- [W200] Decimal(12,3) mapped to REAL in SQLite. Precision may be lost.
-- Hint: Store as TEXT if exact decimal precision is required.
-- [W200] Decimal(12,3) mapped to REAL in SQLite. Precision may be lost.
-- Hint: Store as TEXT if exact decimal precision is required.
CREATE TABLE "walls" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "project_id" INTEGER NOT NULL REFERENCES "projects"("id") ON DELETE CASCADE,
    "storey_id" INTEGER NOT NULL REFERENCES "storeys"("id") ON DELETE CASCADE,
    "wall_type_id" INTEGER REFERENCES "wall_types"("id") ON DELETE RESTRICT,
    "classification" TEXT NOT NULL CHECK ("classification" IN ('innen', 'aussen', 'trag')),
    "name" TEXT,
    "start_x_mm" REAL NOT NULL,
    "start_y_mm" REAL NOT NULL,
    "end_x_mm" REAL NOT NULL,
    "end_y_mm" REAL NOT NULL,
    "thickness_mm" REAL NOT NULL,
    "height_mm" REAL NOT NULL,
    "base_z_mm" REAL DEFAULT 0,
    "material_id" INTEGER REFERENCES "materials"("id") ON DELETE RESTRICT,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL
);

-- [W200] Decimal(12,3) mapped to REAL in SQLite. Precision may be lost.
-- Hint: Store as TEXT if exact decimal precision is required.
-- [W200] Decimal(12,3) mapped to REAL in SQLite. Precision may be lost.
-- Hint: Store as TEXT if exact decimal precision is required.
-- [W200] Decimal(12,3) mapped to REAL in SQLite. Precision may be lost.
-- Hint: Store as TEXT if exact decimal precision is required.
-- [W200] Decimal(12,3) mapped to REAL in SQLite. Precision may be lost.
-- Hint: Store as TEXT if exact decimal precision is required.
CREATE TABLE "openings" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "project_id" INTEGER NOT NULL REFERENCES "projects"("id") ON DELETE CASCADE,
    "wall_id" INTEGER NOT NULL REFERENCES "walls"("id") ON DELETE CASCADE,
    "opening_type" TEXT NOT NULL CHECK ("opening_type" IN ('door', 'window')),
    "offset_mm" REAL NOT NULL,
    "width_mm" REAL NOT NULL,
    "height_mm" REAL NOT NULL,
    "sill_height_mm" REAL DEFAULT 0,
    "name" TEXT,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL
);

-- [W200] Decimal(7,3) mapped to REAL in SQLite. Precision may be lost.
-- Hint: Store as TEXT if exact decimal precision is required.
CREATE TABLE "doors" (
    "opening_id" INTEGER NOT NULL REFERENCES "openings"("id") ON DELETE CASCADE,
    "swing_direction" TEXT NOT NULL CHECK ("swing_direction" IN ('left', 'right')),
    "swing_angle_deg" REAL DEFAULT 90,
    "is_external" INTEGER DEFAULT 0,
    PRIMARY KEY ("opening_id")
);

-- [W200] Decimal(6,3) mapped to REAL in SQLite. Precision may be lost.
-- Hint: Store as TEXT if exact decimal precision is required.
CREATE TABLE "windows" (
    "opening_id" INTEGER NOT NULL REFERENCES "openings"("id") ON DELETE CASCADE,
    "frame_material" TEXT,
    "glazing_type" TEXT,
    "u_value" REAL,
    PRIMARY KEY ("opening_id")
);

CREATE INDEX "idx_storeys_project" ON "storeys" ("project_id");

CREATE INDEX "idx_undo_project_index" ON "undo_commands" ("project_id", "command_index");

CREATE INDEX "idx_rooms_storey" ON "rooms" ("storey_id");

CREATE INDEX "idx_objects_storey" ON "objects" ("storey_id");

CREATE INDEX "idx_slabs_storey" ON "slabs" ("storey_id");

CREATE INDEX "idx_walls_storey" ON "walls" ("storey_id");

CREATE INDEX "idx_openings_wall" ON "openings" ("wall_id");
